### ISSUE TITLE
More generation statistics?

### ISSUE THREAD

**Issue by csterritt** [MaxHalford/gago#12]
Hey --

First of all, thanks so much for such *awesome* documentation.  I've been doing GA stuff for a while, and seeing the "a lot of intellectual fog around the concept of genetic algorithms" quote made me happy.

Anyway, can't wait to use this.

One thing that I miss about using GENESIS system by Grefenstette was that it kept track of the number of gene-bits that were "lost" and those that were "converged".  The lost bits were bits that were (in a specific point on the genome) all 1 or all 0.  The converged ones were mostly the same (maybe 70%?).

It was a very useful metric to let you know when the system had, effectively, hit a local minima.

**Comment by MaxHalford** [comment]
Hello,

Sorry I didn't issue until now, I was a bit busy.

I understand what you mean and at the same time I feel that this only applies to bit genomes. I'm trying to think of a generic way of solving this issue.

What would you think about being able to pass a callback function to a `GA` so that at every generation you can, for example, log additional stuff? If you agree I could start implementing something generic and then you and I could add an example to [gago-examples](https://github.com/MaxHalford/gago-examples) where we do what you are talking about.

**Comment by csterritt** [comment]
Thanks for replying!  Yeah, I think that having the callback would be good -- doing statistics on the entire generation is really what's useful.  Maybe as a separate branch of development, so we can try it out and see if it does any good?

**Comment by MaxHalford** [comment]
Okay I'll create a branch and work on it!

**Comment by MaxHalford** [comment]
Here is the pull request: [gago/pull/13](https://github.com/MaxHalford/gago/pull/13). Tell me what you think about it :)

**Comment by csterritt** [comment]
Gave this a go today, and it works great!  I think it should go in.

Cheers!

**Comment by MaxHalford** [comment]
Okay merging it, thanks for taking a look!
