### ISSUE TITLE
ga.Best is genome with the lowest fitness?

### ISSUE THREAD

**Issue by advanderveer** [MaxHalford/gago#19]
Hey There, I'm new to genetic algorithms and i'm enjoying it a lot. Especially with this awesome library. On thing seems odd to me, as I understand it correctly the method Population.SortByFitness() seems to sort ascendingly and the GA.Best member is the individual at the top of this list. i.e the one with the lowest fitness. 

Is this a defacto standard in the gentic algorithm world? It would logical to have the genome with the highest fitness to be the "best"? 

Thank you!

**Comment by MaxHalford** [comment]
Hello, sorry for the late answer I wasn't available at all.

Indeed `Population.SortByFitness()` sorts individuals by fitness in ascending order, which is rather intuitive. I agree that the "best" individual should intuitively be the one with the highest fitness, because "best" sort of means "highest" culturally. However, in the optimization field the convention is always to minimize a function, not to maximize it. For example in machine learning a loss function is always minimized. In my experience this convention is followed by a lot of researchers and practitioners.

I hope I have brought so,e clarification to your question :)

**Comment by advanderveer** [comment]
Ah! thank you, thats clear, I've learned something new today :)
