### ISSUE TITLE
Evaluate against other genome

### ISSUE THREAD

**Issue by dolanor** [MaxHalford/gago#20]
Hi,
I'm not knowledgeable in the AI/GA domain, and I had an idea in head that confused me.

Now that I sat back, I got it and it's normal, we're trying to optimize a function.

But as I saw it previously, I thought we would evaluate genomes against each other and have the best ones sorted out. But in the current implementation of gago (and in GA in general I guess), the evaluation is against a function, not against another genome.

To explain my idea, an example might help. I have a game with characters that can be created with abilities values (strength, dexterity, constitution) and I would like to know what is the optimum way to dispatch ability point in those abilities to have a good fighter. So I wanted to simulate a fight between 2 genomes to determine a winner as the evaluation. Instead, right now, I just try to optimize ability score because mechanically it will make a better fighter, but it doesn't correspond to the idea I had.

Is this a good idea? Is it applied in other fields/lib? Is it doable already with the current gago?

**Comment by MaxHalford** [comment]
Hello,

I believe it's all a question of formulation.

In your case you have 3 variables (let's call them `x`, `y` and `z`). You also have some budget, which in your case is the number of points you allowed to assign to each variable. Your question is "What is the best way to assign points?".

The thing you are getting mixed up with is the *objective function* (the term objective is super important). You need some way of determining how good an allocation of points is. Yes you can make two genomes fight and use the result as a scoring function. However, you would have to make each one of your genomes compete against the same opponent to make your results *objective*. For example winning against a weak opponent isn't the same as winning against a strong opponent.

You have a lot of possibilities for choosing an external opponent:

- Make each genome fight with the best genome.
- Make each genome fight against a preconfigured genome (like a boss)
- Make each genome fight against a list of preconfigured genomes (like a dungeon)

I hope I was clear! The general idea is that you need a reproducible way to compare genomes, you can't compare apples and oranges, you have to be *objective*.

Please feel free to tell me if I haven't answered your question, I also speak fluent French :)

**Comment by dolanor** [comment]
Ok, I got it. You're right, it's the **objective** that is important.
That's what I kinda guessed after I put my question, so I decided to do a fight against the best genome.
I implemented it, but I didn't know how to access the GA from the genome. So I injected a reference to the GA in the genome: https://github.com/dolanor/dnand/blob/master/cmd/chargen/genetic.go#L88

I guess my implementation is not great since I'm using the current best instead of the best.

But now, would it be easy to implement a non-objective evaluation as a tournament ? From the population of 50, you get the 3 genome who have the best WON VS LOST ratio when fighting every each genome. I don't know if it makes sense in the GA world.

Other than that, thanks for this lib, I wanted to experiment with GA a long time ago, and I finally decided to do it since your lib was there and easy to grasp.

**Comment by MaxHalford** [comment]
Hey again.

Good job! Your code looks fine.

You can indeed customize the way the selection is done. To do so you have to implement a custom `Selector` with the following interface:

```go
type Selector interface {
	Apply(n int, indis Individuals, rng *rand.Rand) (selected Individuals, indexes []int, err error)
	Validate() error
}
```

To start you can copy paste the tournement selection code in `selection.go` and customize it. Instead of sorting the individuals by their fitness make them fight with each other and sort them by the won/lost ratio you mentioned. I've never done anything like it but it should be straightforward to implement. The problem is that the GA will still use the `Evaluate` method for finding the "best" fighter. It really depends what you want to do. You could also compute the won/lost ratio inside the  `Evaluate` method.

Thanks for the kind words!

**Comment by dolanor** [comment]
What is the problem with the fact that the GA will stille use the `Evaluate` method?

I wanted to add, it was my most fun project in long while. So, thanks again!

**Comment by MaxHalford** [comment]
So the stuff that I told you about was relative to selection. You will make genomes fight each other and select the best. But this won't affect the `CurrentBest` and `Best` individuals in the GA because these are selected based on the output of the `Evaluate` method. In other words selection has nothing to do with determining which is the best individual each round.

Did I make things a bit clearer?

**Comment by MaxHalford** [comment]
Can I close the issue @dolanor ?

**Comment by dolanor** [comment]
Yes, actually, you did answer everything. Sorry for not closing already.
